/**
 * SOLARIA & TERRA — Catalog, Tasting Flights, Events & Gifting Data
 */

const SHOP_DATA = {
  products: [
    {
      id: "oil-awake",
      name: "AWAKE — Bold Cold-Pressed EVOO",
      category: "olive-oil",
      type: "Extra Virgin Olive Oil",
      origin: "California Central Coast",
      region: "Santa Ynez Valley, CA",
      varietal: "Coratina & Frantoio Olives",
      flavorProfile: "Fruity & Peppery",
      intensity: "robust", // mild, medium, robust
      intensityStars: "★★★",
      price: 42.00,
      volume: "375 ml (12.7 fl oz)",
      harvestDate: "November 2025 (Single Estate)",
      polyphenols: "620 mg/kg (Ultra-High Antioxidants)",
      acidity: "< 0.14% (Strictly Extra Virgin)",
      smokePoint: "410°F / 210°C",
      rating: 4.95,
      reviewCount: 342,
      badge: "Best Seller",
      badgeType: "terracotta",
      image: "image/oi (1).jpg",
      description: "Crafted for cozy stews, slow roasts, bitter greens, crusty sourdough dipping, and finishing grilled meats. Bottled in opaque UV-protecting white glass to preserve peak living enzymes.",
      tastingNotes: ["Artichoke Hearts", "Wild Arugula", "Black Pepper", "Fresh Cut Grass"],
      pairings: ["Rustic Sourdough Boule", "Ribeye Tagliata", "Charred Broccolini", "Aged Parmesan"]
    },
    {
      id: "oil-alive",
      name: "ALIVE — Vibrant Herbaceous EVOO",
      category: "olive-oil",
      type: "Extra Virgin Olive Oil",
      origin: "California Central Coast",
      region: "Paso Robles, CA",
      varietal: "Arbequina & Picual Olives",
      flavorProfile: "Grassy & Herbaceous",
      intensity: "medium",
      intensityStars: "★★☆",
      price: 40.00,
      volume: "375 ml (12.7 fl oz)",
      harvestDate: "October 2025 (Early Harvest)",
      polyphenols: "540 mg/kg",
      acidity: "< 0.16%",
      smokePoint: "410°F / 210°C",
      rating: 4.92,
      reviewCount: 288,
      badge: "Staff Pick",
      badgeType: "olive",
      image: "image/oi (2).jpg",
      description: "Bright, grassy, and crisp with green tomato vine aromas. Made for crisp salads, flaky sea salt dips, warm grains, delicate fish, and baking olive oil cakes.",
      tastingNotes: ["Green Apple Peel", "Tomato Leaf", "Fresh Almonds", "Mild White Pepper"],
      pairings: ["Heirloom Tomatoes & Burrata", "Grilled Branzino", "Citrus Olive Oil Cake", "Avocado Tartine"]
    },
    {
      id: "oil-lucent",
      name: "LUCENT — Sun-Drenched Lemon Infused",
      category: "infused-oil",
      type: "Agrumato Crushed Olive Oil",
      origin: "California Central Coast",
      region: "Ojai Valley, CA",
      varietal: "Mission Olives & Eureka Lemons",
      flavorProfile: "Citrus & Bright",
      intensity: "mild",
      intensityStars: "★☆☆",
      price: 44.00,
      volume: "375 ml (12.7 fl oz)",
      harvestDate: "December 2025 (Simultaneous Cold Press)",
      polyphenols: "480 mg/kg",
      acidity: "< 0.18%",
      smokePoint: "390°F / 198°C",
      rating: 4.98,
      reviewCount: 412,
      badge: "Award Winner",
      badgeType: "amber",
      image: "image/oi (4).jpg",
      description: "Whole organic Meyer lemons cold-pressed together with early-picked Mission olives in a traditional Mediterranean Agrumato method. Radiates vibrant sunny citrus oils.",
      tastingNotes: ["Meyer Lemon Blossom", "Sweet Grass", "Zesty Citrus Rind", "Smooth Butter"],
      pairings: ["Pan-Seared Scallops", "Shaved Fennel Salad", "Greek Yogurt Parfait", "Grilled Asparagus"]
    },
    {
      id: "oil-rosetta",
      name: "ROSETTA — Tuscan Reserve Single-Estate",
      category: "olive-oil",
      type: "Tuscan Extra Virgin Olive Oil",
      origin: "Tuscany (Italy)",
      region: "Chianti Classico Hills, Italy",
      varietal: "Frantoio, Moraiolo, Leccino",
      flavorProfile: "Fruity & Peppery",
      intensity: "robust",
      intensityStars: "★★★",
      price: 52.00,
      volume: "500 ml (16.9 fl oz)",
      harvestDate: "October 2025",
      polyphenols: "710 mg/kg (Rare Reserve)",
      acidity: "< 0.12%",
      smokePoint: "415°F / 212°C",
      rating: 5.00,
      reviewCount: 174,
      badge: "Reserve Batch",
      badgeType: "olive",
      image: "image/oi (6).jpg",
      description: "Directly imported from a 4th-generation certified organic estate in the Chianti hills. Pronounced peppery throat-catch indicating extraordinary polyphenol density.",
      tastingNotes: ["Cardoon", "Raw Artichoke", "Green Walnut", "Intense White Pepper"],
      pairings: ["Ribollita Tuscan Stew", "Fiorentina Steak", "Carpaccio", "Pecorino Toscano"]
    },
    {
      id: "oil-chili",
      name: "ARSON — Smoky Arbol & Habanero Chili Oil",
      category: "infused-oil",
      type: "Infused Olive Oil",
      origin: "California Central Coast",
      region: "Santa Maria, CA",
      varietal: "Arbequina & Heirloom Chili Peppers",
      flavorProfile: "Spicy Chili & Garlic",
      intensity: "robust",
      intensityStars: "★★★",
      price: 44.00,
      volume: "375 ml (12.7 fl oz)",
      harvestDate: "November 2025",
      polyphenols: "510 mg/kg",
      acidity: "< 0.17%",
      smokePoint: "395°F / 201°C",
      rating: 4.91,
      reviewCount: 220,
      badge: "Crowd Favorite",
      badgeType: "terracotta",
      image: "image/oi (9).jpg",
      description: "Cold-infused with sun-dried red Arbol chilis, smoky chipotle, and cold-pressed garlic. Gives a gorgeous slow crimson bloom without overpowering bitter pungency.",
      tastingNotes: ["Toasted Chili", "Garlic Confit", "Woodsmoke", "Fruity Warmth"],
      pairings: ["Neapolitan Pizza", "Crispy Fried Eggs", "Garlic Prawns", "Cacio e Pepe"]
    },
    {
      id: "vin-trebbiano",
      name: "PARASOL — Raw Champagne & Orange Blossom Vinegar",
      category: "fruit-vinegar",
      type: "Artisanal Fruit Vinegar",
      origin: "California Central Coast",
      region: "Santa Barbara, CA",
      varietal: "Chardonnay Grapes & Navel Oranges",
      flavorProfile: "Citrus & Bright",
      intensity: "mild",
      intensityStars: "★☆☆",
      price: 36.00,
      volume: "200 ml (6.8 fl oz)",
      harvestDate: "Aged 2 Years in Oak Casks",
      polyphenols: "Living Mother Culture",
      acidity: "6% Natural Acidity",
      smokePoint: "Raw Finishing Only",
      rating: 4.89,
      reviewCount: 195,
      badge: "Living Vinegar",
      badgeType: "amber",
      image: "image/oi (12).jpg",
      description: "Fermented naturally from Central Coast wine grapes and fresh Californian oranges. Never heated or pasteurized to retain the active probiotic mother.",
      tastingNotes: ["Golden Apricot", "Orange Blossom Honey", "Crisp Apple", "Brioche"],
      pairings: ["Summer Stonefruit Salads", "Seafood Ceviche", "Craft Cocktails", "Goat Cheese"]
    },
    {
      id: "vin-balsamic-reserve",
      name: "NOCTURNE — 12-Year Oak-Aged Balsamic of Modena",
      category: "balsamic-vinegar",
      type: "Tradizionale IGP Balsamic",
      origin: "Modena (Italy)",
      region: "Emilia-Romagna, Italy",
      varietal: "Trebbiano & Lambrusco Grape Must",
      flavorProfile: "Sweet & Oak-Aged",
      intensity: "robust",
      intensityStars: "★★★",
      price: 58.00,
      volume: "250 ml (8.5 fl oz)",
      harvestDate: "Aged 12 Years in 5 Wood Casks",
      polyphenols: "Concentrated Must",
      acidity: "6.2% Dense Glaze",
      smokePoint: "Raw Drizzling Only",
      rating: 4.99,
      reviewCount: 310,
      badge: "IGP Certified",
      badgeType: "balsamic",
      image: "image/oi (14).jpg",
      description: "Viscous, velvety dark nectar slowly aged through successive barrels of oak, chestnut, cherry, ash, and mulberry wood. Rich syrupy balance of dark plum and fig.",
      tastingNotes: ["Dried Mission Fig", "Dark Cacao", "Black Cherry", "Toasted Oak"],
      pairings: ["Vanilla Bean Gelato", "Fresh Strawberries", "Parmigiano-Reggiano Chunks", "Roast Duck"]
    },
    {
      id: "vin-blackberry",
      name: "RUBY DUSK — Wild Blackberry & Merlot Vinegar",
      category: "fruit-vinegar",
      type: "Botanical Fruit Vinegar",
      origin: "California Central Coast",
      region: "Sonoma County, CA",
      varietal: "Merlot Wine & Wild Blackberries",
      flavorProfile: "Sweet & Oak-Aged",
      intensity: "medium",
      intensityStars: "★★☆",
      price: 38.00,
      volume: "200 ml (6.8 fl oz)",
      harvestDate: "Aged 18 Months",
      polyphenols: "Wild Berry Anthocyanins",
      acidity: "5.8% Acidity",
      smokePoint: "Finishing & Reductions",
      rating: 4.93,
      reviewCount: 162,
      badge: "Limited Release",
      badgeType: "balsamic",
      image: "image/oi (16).jpg",
      description: "Made by infusing crushed wild coastal blackberries into barrel-fermented Merlot wine vinegar. Lends brilliant jewel tones and bright berry acidity to reductions.",
      tastingNotes: ["Ripe Marionberry", "Cranberry Tartness", "Vanilla Bean", "Cedar"],
      pairings: ["Duck Breast Salad", "Roast Beetroot & Goat Cheese", "Sparkling Soda Shrub", "Blue Cheese"]
    },
    {
      id: "set-duo-tasting",
      name: "THE ESSENTIAL DUO — Awake & Alive Set",
      category: "sets",
      type: "Curated EVOO Set",
      origin: "California Central Coast",
      region: "Santa Barbara County, CA",
      varietal: "Dual Harvest Blend",
      flavorProfile: "Fruity & Peppery",
      intensity: "medium",
      intensityStars: "★★☆",
      price: 78.00,
      volume: "2 x 375 ml Bottles",
      harvestDate: "Current 2025/2026 Harvest",
      polyphenols: "580 mg/kg Avg",
      acidity: "< 0.15%",
      smokePoint: "410°F / 210°C",
      rating: 4.97,
      reviewCount: 520,
      badge: "Most Gifted",
      badgeType: "terracotta",
      image: "image/oi (19).jpg",
      description: "Our signature foundational pairing in an embossed gift sleeve with a bespoke golden pour spout. The ultimate kitchen essential duo for everyday luxury.",
      tastingNotes: ["Robust Warmth (Awake)", "Herbaceous Green (Alive)", "Fresh Crushed Olives"],
      pairings: ["Complete Culinary Cooking & Finishing", "Salads, Breads, Proteins & Roasting"]
    },
    {
      id: "set-mini-flight",
      name: "THE MINI FLIGHT — 4 Petite Tasting Bottles",
      category: "sets",
      type: "Boutique Tasting Set",
      origin: "California & Mediterranean",
      region: "Multi-Estate Collection",
      varietal: "Awake, Alive, Lucent & Parasol",
      flavorProfile: "Citrus & Bright",
      intensity: "medium",
      intensityStars: "★★☆",
      price: 68.00,
      volume: "4 x 100 ml Bottles",
      harvestDate: "2025 Harvest Flight",
      polyphenols: "Full Spectrum",
      acidity: "Various",
      smokePoint: "Up to 410°F",
      rating: 4.96,
      reviewCount: 380,
      badge: "Tasting Bar Edition",
      badgeType: "amber",
      image: "image/oi (22).jpg",
      description: "Our complete tasting bar experience packaged into four keepsake glass bottles with our printed sommelier tasting wheel and food pairing guide.",
      tastingNotes: ["Full spectrum olive varietals from bright citrus to peppery robust finish"],
      pairings: ["Home Tasting Flights", "Dinner Party Pairings", "Host Gifting"]
    },
    {
      id: "oil-koroneiki",
      name: "AURA — Peloponnese Single-Grove Koroneiki",
      category: "olive-oil",
      type: "Greek Extra Virgin Olive Oil",
      origin: "Peloponnese (Greece)",
      region: "Kalamata, Messenia, Greece",
      varietal: "100% Ancient Koroneiki Trees",
      flavorProfile: "Grassy & Herbaceous",
      intensity: "medium",
      intensityStars: "★★☆",
      price: 46.00,
      volume: "500 ml (16.9 fl oz)",
      harvestDate: "November 2025",
      polyphenols: "680 mg/kg",
      acidity: "< 0.13%",
      smokePoint: "415°F / 212°C",
      rating: 4.94,
      reviewCount: 140,
      badge: "Single Grove",
      badgeType: "olive",
      image: "image/oi (25).jpg",
      description: "Hand-harvested from centenarian coastal trees sloping down to the Ionian Sea. Smooth emerald body with lingering notes of wild thyme and green banana.",
      tastingNotes: ["Wild Oregano", "Green Banana", "Fresh Thyme", "Silky Finish"],
      pairings: ["Greek Village Horiatiki Salad", "Grilled Octopus", "Spanakopita", "Feta in Filo"]
    },
    {
      id: "set-chef-quintet",
      name: "THE CHEF’S QUINTET — Complete Harvest Vault",
      category: "sets",
      type: "Signature Collector Set",
      origin: "California & Mediterranean",
      region: "Curated Estate Cellars",
      varietal: "5 Full-Sized Estate Bottles",
      flavorProfile: "Fruity & Peppery",
      intensity: "robust",
      intensityStars: "★★★",
      price: 185.00,
      volume: "5 x 375 ml Full Bottles",
      harvestDate: "Reserve Cellar 2025/2026",
      polyphenols: "Up to 710 mg/kg",
      acidity: "< 0.15%",
      smokePoint: "Up to 415°F",
      rating: 5.00,
      reviewCount: 94,
      badge: "Collector's Vault",
      badgeType: "terracotta",
      image: "image/oi (28).jpg",
      description: "Includes Awake, Alive, Lucent Lemon, Arson Chili, and Nocturne 12-Year Balsamic, nestled in our handcrafted wooden heirloom keepsake crate.",
      tastingNotes: ["The entire chromatic spectrum of cold-pressed oils & aged vineyard vinegars"],
      pairings: ["Gourmet Culinary Repertoire", "Master Sommelier Dinners"]
    }
  ],

  events: [
    {
      id: "event-grand-flight",
      title: "The Grand Single-Estate Flight & Sensory Analysis",
      category: "guided-tasting",
      duration: "75 Minutes",
      pricePerPerson: 55,
      capacity: "14 Guests per Slot",
      leadSommelier: "Elena Rostova (Master Olive Oil Sommelier)",
      image: "image/oi (32).jpg",
      description: "Step up to our boutique tasting counter for a guided sensory deep dive. Learn the official blue-glass blind tasting protocol, detect harvest fresh polyphenols, and pair 6 estate oils & 4 vinegars with artisanal sourdough, local farmstead cheeses, and seasonal delicacies.",
      included: [
        "6 Single-Estate EVOO Tastings (California & Mediterranean)",
        "4 Barrel-Aged Fruit & Traditional Balsamics",
        "Artisanal Sourdough, Whipped Sea Salt Butter & Organic Raw Crudités",
        "Local Santa Ynez Sheep & Goat Cheese Pairings",
        "Official Tasting Flight Certificate & 15% Boutique Voucher"
      ],
      schedule: ["Tuesday 3:00 PM", "Thursday 5:30 PM", "Saturday 11:30 AM", "Saturday 4:00 PM", "Sunday 2:00 PM"]
    },
    {
      id: "event-sommelier-masterclass",
      title: "Masterclass: Olive Oil Sommelier Level I Sensory Workshop",
      category: "workshop",
      duration: "120 Minutes",
      pricePerPerson: 95,
      capacity: "10 Guests per Slot",
      leadSommelier: "Marco Bellini (International Olive Oil Judge)",
      image: "image/oi (34).jpg",
      description: "An intensive masterclass on olive varietals, milling chemistry (polyphenols, acidity, smoke points), defect detection (rancidity, fustiness), and professional food pairing principles. Includes guided palate calibration and blind sensory evaluation tests.",
      included: [
        "10 Guided Curated Samples & Defect Calibration Oils",
        "Sensory Evaluation Palate Notebook & Aroma Wheel",
        "Heirloom Charcuterie & Truffle Crostini Plate",
        "Take-home 200ml Limited Reserve Single-Grove Bottle",
        "Official Certificate of Palate Completion"
      ],
      schedule: ["Friday 6:00 PM", "Sunday 11:00 AM"]
    },
    {
      id: "event-balsamic-mixology",
      title: "Olive Oil & Balsamic Mixology: Shrubs, Dressings & Elixirs",
      category: "workshop",
      duration: "90 Minutes",
      pricePerPerson: 75,
      capacity: "12 Guests per Slot",
      leadSommelier: "Camille Dupont (Botanical Mixologist)",
      image: "image/oi (35).jpg",
      description: "Discover how cold-pressed botanical oils and living fruit vinegars transform modern craft mixology, botanical spritzes, zero-proof shrubs, and emulsified dressings. Hands-on cocktail & mocktail shaking session.",
      included: [
        "3 Crafted Botanical Cocktails or Zero-Proof Shrubs",
        "Hands-on Emulsified Vinaigrette & Gastrique Workshop",
        "Mediterranean Tapas & Sea Salt Focaccia Board",
        "Custom Recipe Booklet & Golden Bar Pour Spout"
      ],
      schedule: ["Wednesday 6:00 PM", "Saturday 6:30 PM"]
    },
    {
      id: "event-private-cellar",
      title: "Private Boutique Cellar Soirée & After-Hours Reception",
      category: "private-hire",
      duration: "3 Hours",
      pricePerPerson: 140,
      capacity: "Up to 30 Guests",
      leadSommelier: "Private Sommelier Team",
      image: "image/oi (36).jpg",
      description: "Exclusive private hire of our sunlit boutique and private cellar patio for corporate celebrations, bridal parties, anniversaries, and VIP culinary gatherings with full sommelier service.",
      included: [
        "Private Access to entire boutique & garden terrace",
        "Full Guided Tasting Flight + Unlimited Pouring Bar",
        "Bespoke Grazing Table & Artisan Pincho Buffets",
        "Personalized Custom Bottled Favors for all guests"
      ],
      schedule: ["Available 7 Days a week by appointment"]
    }
  ],

  dishPairings: [
    {
      id: "pairing-burrata",
      dish: "Heirloom Burrata & Sun Tomatoes",
      emoji: "🍅",
      recommendedOil: "ALIVE — Vibrant Herbaceous EVOO",
      recommendedVinegar: "PARASOL — Raw Champagne Vinegar",
      description: "The grassy, tomato-vine aroma of Alive elevates the milky sweetness of fresh burrata, while a splash of Parasol adds champagne sparkle."
    },
    {
      id: "pairing-sourdough",
      dish: "Warm Sourdough & Flaky Salt",
      emoji: "🥖",
      recommendedOil: "AWAKE — Bold Cold-Pressed EVOO",
      recommendedVinegar: "NOCTURNE — 12-Yr Aged Balsamic",
      description: "A deep, robust oil with peppery finish that cuts through rich fermented dough, accented with syrupy aged Modena balsamic drops."
    },
    {
      id: "pairing-seafood",
      dish: "Grilled Sea Bass or Scallops",
      emoji: "🐟",
      recommendedOil: "LUCENT — Lemon Crushed Agrumato",
      recommendedVinegar: "PARASOL — Orange Blossom Vinegar",
      description: "Crushed Meyer lemon oils provide clean brightness without citric acid curdling delicate pan-seared fish."
    },
    {
      id: "pairing-steak",
      dish: "Charred Ribeye & Bitter Greens",
      emoji: "🥩",
      recommendedOil: "ROSETTA — Tuscan Reserve Chianti",
      recommendedVinegar: "RUBY DUSK — Wild Blackberry Vinegar",
      description: "High polyphenol intensity from Tuscan Frantoio olives balances rich caramelized marbling with a hint of dark blackberry acid."
    },
    {
      id: "pairing-pizza",
      dish: "Wood-Fired Pizza & Burrata Tart",
      emoji: "🍕",
      recommendedOil: "ARSON — Smoky Arbol Chili Oil",
      recommendedVinegar: "NOCTURNE — Aged Balsamic Glaze",
      description: "Warm smoky heat creates irresistible contrast against creamy buffalo mozzarella and blistering leopard-crust dough."
    },
    {
      id: "pairing-dessert",
      dish: "Vanilla Gelato & Dark Chocolate",
      emoji: "🍨",
      recommendedOil: "AWAKE EVOO or LUCENT Lemon",
      recommendedVinegar: "NOCTURNE — 12-Yr Aged Balsamic",
      description: "The classic Modena secret: rich aged balsamic drizzled over cold Madagascar vanilla bean ice cream with flaky sea salt."
    }
  ]
};
